/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ReportesController;
import Modelo.vo.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class JFrame_Informes extends javax.swing.JFrame {

    JTable tablaInformes;
    ResultSet rs;

    /**
     * Creates new form JFrame_Informes
     */
    public JFrame_Informes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void inicializarComponentes() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_Opcion = new javax.swing.JComboBox<>();
        btn_generarReporte = new javax.swing.JButton();
        SP_Contenedor = new javax.swing.JScrollPane();
        jTableInicial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lb_TituloTabla = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Generación de Reportes");

        cb_Opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lideres", "Proyectos", "Compras" }));

        btn_generarReporte.setText("Generar Reporte");
        btn_generarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarReporteActionPerformed(evt);
            }
        });

        jTableInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        SP_Contenedor.setViewportView(jTableInicial);

        jLabel2.setText("Seleccione una categoria:");

        lb_TituloTabla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TituloTabla.setText("Reportes");

        lb_descripcion.setText("Descripción del reporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SP_Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(lb_TituloTabla)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_descripcion)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cb_Opcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_generarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generarReporte)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lb_TituloTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lb_descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarReporteActionPerformed
        DefaultTableModel dfm = new DefaultTableModel();
        tablaInformes = this.jTableInicial;
        tablaInformes.setModel(dfm);

        String Opcion = this.cb_Opcion.getSelectedItem().toString();

        switch (Opcion) {
            case "Lideres":
                dfm.setColumnIdentifiers(new Object[]{"ID Lider", "Nombre", "Primer Apellido", "Ciudad de Residencia"});
                ArrayList<LiderVo> ListaLideres = ReportesController.getinformacionLideres();
                try {
                    for ( LiderVo Lider : ListaLideres) {
                        dfm.addRow(new Object[]{Lider.getID_Lider(), Lider.getNombre(),Lider.getPrimer_Apellido(),Lider.getCiudad_Residencia()});
                    }
                    this.lb_TituloTabla.setText("Reporte de Lideres");
                    this.lb_descripcion.setText("Se genera un reporte con la infromación de los lideres, ordenado por la ciudad de residencia.");
                }
                catch(Exception e){
                }
                break;
            case "Proyectos":
                dfm.setColumnIdentifiers(new Object[]{"ID Proyecto", "Constructora", "Numero de Habitaciones", "Ciudad"});
                ArrayList<ProyectoVo> ListaProyectos = ReportesController.getinformacionProyectos();
                try {
                    for ( ProyectoVo Proyecto : ListaProyectos) {
                        dfm.addRow(new Object[]{Proyecto.getID_Proyecto(), Proyecto.getConstructora(),Proyecto.getNumero_Habitaciones(),Proyecto.getCiudad()});
                    }
                    this.lb_TituloTabla.setText("Reporte de Proyectos");
                    this.lb_descripcion.setText("Se genera un reporte con la infromación de los proyectos de casa campestre en Santa Marta, Cartagena y Barranquilla.");
                }
                catch(Exception e){
                }
                break;                
            case "Compras":
                dfm.setColumnIdentifiers(new Object[]{"ID Compra", "Constructora", "Banco Vinculado"});
                ArrayList<ComprasVo> listaCompras = ReportesController.getinformacionCompras();
                try {
                    for ( ComprasVo Compra : listaCompras) {
                        dfm.addRow(new Object[]{Compra.getID_Compra(), Compra.getConstructora(),Compra.getBanco_Vinculado()});
                    }
                    this.lb_TituloTabla.setText("Reporte de Compras");
                    this.lb_descripcion.setText("Se genera un reporte con la infromación de las compras realizadas a homecenter en la ciudad de Salento.");
                }
                catch(Exception e){
                }
                break;       
            default:
                
        }

    }//GEN-LAST:event_btn_generarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Informes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SP_Contenedor;
    private javax.swing.JButton btn_generarReporte;
    private javax.swing.JComboBox<String> cb_Opcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTableInicial;
    private javax.swing.JLabel lb_TituloTabla;
    private javax.swing.JLabel lb_descripcion;
    // End of variables declaration//GEN-END:variables

}
